# Generated by Django 5.0.4 on 2024-05-24 16:53

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('publishdate', models.DateTimeField(auto_now_add=True)),
                ('authorid', models.IntegerField(default=0)),
                ('featuredimage', models.ImageField(default=0, upload_to='uploads/')),
                ('content', tinymce.models.HTMLField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
