# Generated by Django 5.0.4 on 2024-04-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogbreezeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='authorid',
            field=models.IntegerField(default=0),
        ),
    ]
