# Generated by Django 5.0.4 on 2024-06-06 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogbreezeapp', '0003_alter_blog_authorid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, default='', unique=True),
        ),
    ]
