# Generated by Django 5.0.4 on 2024-06-11 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogbreezeapp', '0004_alter_blog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='featuredimage',
            field=models.ImageField(default=0, upload_to='uploads/'),
        ),
    ]
