# Generated by Django 5.0.4 on 2024-05-27 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogbreezeapp', '0005_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
