# Generated by Django 5.0.4 on 2024-05-21 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogbreezeapp', '0005_alter_blog_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='publishdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
