# Generated by Django 5.0.4 on 2024-06-01 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogbreezeapp', '0006_rename_users_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
