# Generated by Django 5.0.4 on 2024-06-11 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogbreezeapp', '0006_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
