# Generated by Django 5.0.4 on 2024-05-21 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogbreezeapp', '0007_category_blog_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
